artifact_location: file:///home/ether/Desktop/Mini-conda/Project/MLflow/scripts/artifacts/896835410358327612
creation_time: 1717103935085
experiment_id: '896835410358327612'
last_update_time: 1717103935085
lifecycle_stage: active
name: nyc-assignment-arti-experiment
